#ifndef ADAFRUIT_INA219_GLOBAL_H
#define ADAFRUIT_INA219_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADAFRUIT_INA219_LIBRARY)
#  define ADAFRUIT_INA219SHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADAFRUIT_INA219SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADAFRUIT_INA219_GLOBAL_H
