#ifndef NEXHARDWARE_GLOBAL_H
#define NEXHARDWARE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXHARDWARE_LIBRARY)
#  define NEXHARDWARESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEXHARDWARESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXHARDWARE_GLOBAL_H
