#ifndef NEXTOUCH_GLOBAL_H
#define NEXTOUCH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXTOUCH_LIBRARY)
#  define NEXTOUCHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEXTOUCHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXTOUCH_GLOBAL_H
