#ifndef NEXTIONRASPBERRYPI_GLOBAL_H
#define NEXTIONRASPBERRYPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXTIONRASPBERRYPI_LIBRARY)
#  define NEXTIONRASPBERRYPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEXTIONRASPBERRYPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXTIONRASPBERRYPI_GLOBAL_H
