#ifndef NEXPROGRESSBAR_GLOBAL_H
#define NEXPROGRESSBAR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXPROGRESSBAR_LIBRARY)
#  define NEXPROGRESSBARSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEXPROGRESSBARSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXPROGRESSBAR_GLOBAL_H
