#ifndef NEXVARIABLE_GLOBAL_H
#define NEXVARIABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXVARIABLE_LIBRARY)
#  define NEXVARIABLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NEXVARIABLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXVARIABLE_GLOBAL_H
